{
 "title": "vLLM & GuideLLM Model Metrics",
 "description": "Monitoring vLLM Inference Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "model_name",
    "label": "vLLM Model",
    "query": {
     "query": "label_values(vllm:generation_tokens_total{namespace=\"$namespace\"}, model_name)"
    }
   },
   {
    "name": "guidellm_model",
    "label": "GuideLLM Model",
    "query": {
     "query": "label_values(guidellm_total_requests{namespace=\"$namespace\"}, model)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "vLLM Generation Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (model_name)(rate(vllm:generation_tokens_total{namespace=\"$namespace\",model_name=~\"$model_name\"}[5m]))",
     "legendFormat": "{{model_name}} tokens/sec"
    }
   ]
  },
  {
   "title": "vLLM Prompt Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (model_name)(rate(vllm:prompt_tokens_total{namespace=\"$namespace\",model_name=~\"$model_name\"}[5m]))",
     "legendFormat": "{{model_name}} tokens/sec"
    }
   ]
  },
  {
   "title": "E2E Request Latency",
   "type": "timeseries",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{namespace=\"$namespace\",model_name=~\"$model_name\"}[5m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{namespace=\"$namespace\",model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{namespace=\"$namespace\",model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{namespace=\"$namespace\",model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(vllm:e2e_request_latency_seconds_sum{namespace=\"$namespace\",model_name=~\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:e2e_request_latency_seconds_count{model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Scheduler State",
   "type": "timeseries",
   "description": "Number of requests in RUNNING, WAITING, and SWAPPED state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (model_name)(vllm:num_requests_running{namespace=\"$namespace\",model_name=~\"$model_name\"})",
     "legendFormat": "{{model_name}} running"
    },
    {
     "expr": "sum by (model_name)(vllm:num_requests_swapped{namespace=\"$namespace\",model_name=~\"$model_name\"})",
     "legendFormat": "{{model_name}} swapped"
    },
    {
     "expr": "sum by (model_name)(vllm:num_requests_waiting{namespace=\"$namespace\",model_name=~\"$model_name\"})",
     "legendFormat": "{{model_name}} waiting"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Tensor Core Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{namespace=\"$namespace\",instance=~\".+\", gpu=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Prompt Length",
   "type": "heatmap",
   "description": "Heatmap of request prompt length",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_prompt_tokens_bucket{namespace=\"$namespace\",model_name=~\"$model_name\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Generation Length",
   "type": "heatmap",
   "description": "Heatmap of request generation length",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_generation_tokens_bucket{namespace=\"$namespace\",model_name=~\"$model_name\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Successfully Processed Requests",
   "type": "timeseries",
   "description": "Number of finished requests by their finish reason: either an EOS token was generated or the max sequence length was reached.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(finished_reason) (increase(vllm:request_success_total{namespace=\"$namespace\",model_name=~\"$model_name\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "timeseries",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vllm:gpu_cache_usage_perc{namespace=\"$namespace\",model_name=~\"$model_name\"}",
     "legendFormat": "GPU Cache Usage"
    },
    {
     "expr": "vllm:cpu_cache_usage_perc{namespace=\"$namespace\",model_name=~\"$model_name\"}",
     "legendFormat": "CPU Cache Usage"
    }
   ]
  },
  {
   "title": "Time Per Output Token Latency",
   "type": "timeseries",
   "description": "Inter token latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{namespace=\"$namespace\",model_name=~\"$model_name\"}[5m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{namespace=\"$namespace\",model_name=~\"$model_name\"}[5m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{namespace=\"$namespace\",model_name=~\"$model_name\"}[5m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{namespace=\"$namespace\",model_name=~\"$model_name\"}[5m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(vllm:time_per_output_token_seconds_sum{namespace=\"$namespace\",model_name=~\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:time_per_output_token_seconds_count{model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Time To First Token Latency",
   "type": "timeseries",
   "description": "P50, P90, P95, and P99 TTFT latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{namespace=\"$namespace\",model_name=~\"$model_name\"}[5m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{namespace=\"$namespace\",model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{namespace=\"$namespace\",model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{namespace=\"$namespace\",model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(vllm:time_to_first_token_seconds_sum{namespace=\"$namespace\",model_name=~\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:time_to_first_token_seconds_count{model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "GuideLLM Request Latency (P95)",
   "type": "timeseries",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "clamp_min(max_over_time(guidellm_request_latency_p95_seconds{namespace=\"$namespace\",model=~\"$guidellm_model\"}[1h]) or vector(0), 0)"
    }
   ]
  },
  {
   "title": "GuideLLM Throughput (Requests/sec)",
   "type": "timeseries",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "clamp_min(max_over_time(guidellm_throughput_requests_per_second{namespace=\"$namespace\",model=~\"$guidellm_model\"}[1h]) or vector(0), 0)"
    }
   ]
  },
  {
   "title": "GuideLLM Time to First Token (P95)",
   "type": "timeseries",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "clamp_min(max_over_time(guidellm_ttft_p95_seconds{namespace=\"$namespace\",model=~\"$guidellm_model\"}[1h]) or vector(0), 0)"
    }
   ]
  },
  {
   "title": "GuideLLM Request Success Rate",
   "type": "timeseries",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_min(max_over_time(guidellm_request_success_rate{namespace=\"$namespace\",model=~\"$guidellm_model\"}[1h]) or vector(0), 0)"
    }
   ]
  }
 ]
}